### ISSUE TITLE
Circletwerk has been deprecated

### ISSUE THREAD

**Issue by zuron7** [HackathonHackers/groups#30]
The link(http://hh.gd/circle) to circletwerk has to be changed to point to Cirque du Twerq.
https://www.facebook.com/groups/HHCirqueDuTwerque/

**Comment by bryangarza** [comment]
Merged a PR to remove CT. Do you want to PR with the new URL?

**Comment by nsgomez** [comment]
CdT is no longer affiliated with HH so this PR can be closed.
